// src/lib/components/MarkdownRenderer.svelte
<script>
    import { resolveVariables, parseMarkdown } from "$lib/utils/utils.js";

    let {
        content,
        variables = {},
        startOffset = 1,
        continuous = false,
        tierStyles = [],
        class: className = "",
        onVariableClick,
    } = $props();

    let resolved = $derived(resolveVariables(content, variables));
    let htmlContent = $derived(
        parseMarkdown(resolved, startOffset, continuous, tierStyles),
    );

    /** @param {MouseEvent} e */
    function handleClick(e) {
        const target = /** @type {HTMLElement} */ (e.target).closest(
            "[data-variable]",
        );
        if (target && onVariableClick) {
            e.stopPropagation();
            const rect = target.getBoundingClientRect();
            const variablePath = target.getAttribute("data-variable");
            if (variablePath) {
                onVariableClick(variablePath, rect);
            }
        }
    }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
    onclick={handleClick}
    class={`markdown-content prose prose-slate max-w-none ${className}`}
>
    {@html htmlContent}
</div>

// src/components/MarkdownRenderer.jsx
import React, { useMemo } from 'react';
import { resolveVariables, parseMarkdown } from '../utils';

const MarkdownRenderer = ({ content, variables = {}, startOffset = 1, continuous = false, tierStyles = [], className = "", onVariableClick }) => {
    const resolved = useMemo(() => resolveVariables(content, variables), [content, variables]);
    const htmlContent = useMemo(() => parseMarkdown(resolved, startOffset, continuous, tierStyles), [resolved, startOffset, continuous, tierStyles]);

    const handleClick = (e) => {
        const target = e.target.closest('[data-variable]');
        if (target && onVariableClick) {
            e.stopPropagation();
            const rect = target.getBoundingClientRect();
            const variablePath = target.getAttribute('data-variable');
            onVariableClick(variablePath, rect);
        }
    };

    return <div onClick={handleClick} className={`markdown-content prose prose-slate max-w-none ${className}`} dangerouslySetInnerHTML={{ __html: htmlContent }} />;
};

export default MarkdownRenderer;
