// src/components/Login.jsx
import React, { useState } from 'react';
import { pb } from '../lib/pocketbase';
import Icon from './Icon';

export default function Login({ onLogin }) {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError(null);

        try {
            const authData = await pb.collection('users').authWithPassword(email, password);
            onLogin(authData.record);
        } catch (err) {
            console.error("Login failed", err);
            setError("Invalid email or password.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-slate-100">
            <div className="bg-white p-10 rounded-2xl shadow-xl w-full max-w-md border border-slate-200">
                <div className="flex flex-col items-center mb-8 gap-4">
                    <div className="bg-indigo-600 p-3 rounded-xl text-white shadow-lg">
                        <Icon name="Layout" size={32} />
                    </div>
                    <h1 className="text-2xl font-black text-slate-800 uppercase tracking-tight">DocAssemble</h1>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                    <div>
                        <label className="block text-xs font-black uppercase text-slate-400 mb-2 tracking-widest">Email</label>
                        <input
                            type="email"
                            required
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            className="w-full px-4 py-3 rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none transition-all font-medium"
                            placeholder="attorney@firm.com"
                        />
                    </div>
                    <div>
                        <label className="block text-xs font-black uppercase text-slate-400 mb-2 tracking-widest">Password</label>
                        <input
                            type="password"
                            required
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className="w-full px-4 py-3 rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none transition-all font-medium"
                            placeholder="••••••••"
                        />
                    </div>

                    {error && (
                        <div className="p-3 bg-red-50 text-red-600 text-xs font-bold rounded-lg flex items-center gap-2">
                            <Icon name="AlertCircle" size={16} />
                            {error}
                        </div>
                    )}

                    <button
                        type="submit"
                        disabled={loading}
                        className="w-full py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-black uppercase tracking-widest transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                    >
                        {loading ? <Icon name="Loader2" className="animate-spin" /> : <Icon name="LogIn" />}
                        {loading ? "Signing In..." : "Sign In"}
                    </button>
                </form>
            </div>
        </div>
    );
}

// src/routes/login/+page.svelte
<script>
    import { pb } from "$lib/pocketbase.svelte";
    import { user } from "$lib/stores/app";

    /** @type {{ onLogin?: (record: any) => void }} */
    let { onLogin } = $props();

    let email = $state("");
    let password = $state("");
    let loading = $state(false);
    let error = $state(null);

    /** @param {SubmitEvent} e */
    async function handleSubmit(e) {
        e.preventDefault();
        loading = true;
        error = null;

        try {
            const authData = await pb
                .collection("users")
                .authWithPassword(email, password);
            user.set(authData.record);
            if (onLogin) onLogin(authData.record);
        } catch (err) {
            console.error("Login failed", err);
            error = "Invalid email or password.";
        } finally {
            loading = false;
        }
    }
</script>

<div class="min-h-screen flex items-center justify-center bg-slate-100">
    <div
        class="bg-white p-10 rounded-2xl shadow-xl w-full max-w-md border border-slate-200"
    >
        <div class="flex flex-col items-center mb-8 gap-4">
            <div class="bg-indigo-600 p-3 rounded-xl text-white shadow-lg">
                <Icon name="Layout" size={32} />
            </div>
            <h1
                class="text-2xl font-black text-slate-800 uppercase tracking-tight"
            >
                DocAssemble
            </h1>
        </div>

        <form onsubmit={handleSubmit} class="space-y-6">
            <div>
                <label
                    for="email"
                    class="block text-xs font-black uppercase text-slate-400 mb-2 tracking-widest"
                    >Email</label
                >
                <input
                    id="email"
                    type="email"
                    required
                    bind:value={email}
                    class="w-full px-4 py-3 rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none transition-all font-medium"
                    placeholder="attorney@firm.com"
                />
            </div>
            <div>
                <label
                    for="password"
                    class="block text-xs font-black uppercase text-slate-400 mb-2 tracking-widest"
                    >Password</label
                >
                <input
                    id="password"
                    type="password"
                    required
                    bind:value={password}
                    class="w-full px-4 py-3 rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none transition-all font-medium"
                    placeholder="••••••••"
                />
            </div>

            {#if error}
                <div
                    class="p-3 bg-red-50 text-red-600 text-xs font-bold rounded-lg flex items-center gap-2"
                >
                    <Icon name="AlertCircle" size={16} />
                    {error}
                </div>
            {/if}

            <button
                type="submit"
                disabled={loading}
                class="w-full py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-black uppercase tracking-widest transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
                {#if loading}
                    <Icon name="Loader2" class="animate-spin" />
                    <span>Signing In...</span>
                {:else}
                    <Icon name="LogIn" />
                    <span>Sign In</span>
                {/if}
            </button>
        </form>
    </div>
</div>
